---
title: "Refugee Integration Paper Descriptives"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 4
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.retina = 4)
knitr::opts_chunk$set(fig.pos = 'H')
```


```{r}
# Libraries
pacman::p_load(tidyverse, readxl, janitor, lubridate, extrafont, hrbrthemes, sf, ggcorrplot, plotly, ggradar, estimatr, texreg)
extrafont::loadfonts()

# Parameters
df_baseline <- 
  read_csv(here::here("data", "Rapid_response_baseline_cleaned_all_consent.csv")) %>%
  inner_join(read_csv(here::here("data", "weights.csv")), by = "study_ID") %>% 
  filter(yearArrive >= 2010) %>% 
  mutate(
    years_in_us = 2020 - yearArrive,
    age_at_arrival = yearArrive - birthYear,
    female = recode(gender, "Male" = "0", "Female" = "1", .default = "0") %>% as.character %>% parse_integer(),
    unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "Yes", "1", unemploymentBeneBaseline),
    unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "No", "0", unemploymentBeneBaseline),
    unemployment = unemploymentBeneBaseline %>% as.integer()
  )
```


```{r}
# extracting data for dlaitin on box
# df_baseline %>%
#   select(-contains(c("name", "numb", "phone", "cell", "mobile", "mail", "contact", "address"))) %>%
#   relocate(ResponseID, ResponseSet, weight) %>% 
#   write_csv(here::here("data", "baseline_data_with_weights_de-identified_11.03.2020.csv"))
#df_baseline %>% select(contains("12"))
```


## Distribution

### General

```{r}
df_baseline %>% 
  ggplot(aes(ipl12s, stat(density), weight = weight)) +
  geom_histogram(color = "black", fill = "grey") +
  geom_density() +
  theme_ipsum()
```

```{r, out.width = "100%"}
df_baseline %>% 
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(score, weight = weight)) +
  geom_density(color = "black", fill = "grey", alpha = 0.5) +
  facet_wrap(vars(measure)) +
  theme_ipsum()
```

Correlations

```{r}
x <-df_baseline %>% select(contains("12s"))
ggcorrplot(cor(x, use = "pairwise.complete.obs"), hc.order = TRUE, type = "lower", p.mat = cor_pmat(x), insig = "blank", lab = TRUE)
rm(x)
```

### Spatial

#### Overall

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        ipl12s = mean(ipl12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = ipl12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "ipl12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Linguistic

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        ling12s = mean(ling12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = ling12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "ling12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Political

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        pol12s = mean(pol12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = pol12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "pol12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Social

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        soc12s = mean(soc12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = soc12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "soc12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Economic

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        econ12s = mean(econ12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = econ12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "econ12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Psychological

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        psy12s = mean(psy12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = psy12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "psy12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```

#### Navigational

```{r, out.width = "100%"}
plot <-
  ussf::boundaries(geography = "state") %>%
  select(stateCurrent = NAME) %>% 
  left_join(
    df_baseline %>% 
      mutate(
        stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
        stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent)
      ) %>% 
      group_by(stateCurrent) %>% 
      summarize(
        nav12s = mean(nav12s, na.rm = T) %>% round(2),
        weight = mean(weight, na.rm = T)
      ),
    by = "stateCurrent"
  ) %>% 
  ggplot(aes(fill = nav12s, weight = weight, text = stateCurrent)) +
  geom_sf(size = 0.3, show.legend = F) +
  scale_fill_viridis_c() +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplotly(plot, tooltip = c("stateCurrent", "nav12s")) %>% 
  layout(xaxis = list(autorange = TRUE), yaxis = list(autorange = TRUE))
```


## Descriptives

```{r, eval=F}
df_baseline %>% select(contains("age"))
```


### Year of arrival

```{r}
df_baseline %>% 
  group_by(yearArrive) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>% 
  filter(yearArrive >= 2010) %>% 
  ggplot(aes(factor(yearArrive), ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```


```{r, out.width="100%"}
df_baseline %>%
  group_by(yearArrive) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  drop_na(yearArrive) %>% 
  filter(yearArrive >= 2010) %>% 
  mutate(yearArrive = as.integer(yearArrive)) %>% 
  ggplot(aes(yearArrive, score, weight = weight)) +
  geom_col() +
  scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  facet_wrap(vars(measure))
```

Regressions

```{r}
lm1 <- df_baseline %>% lm_robust(ipl12s ~ yearArrive, data = .)
lm2 <- df_baseline %>% lm_robust(ling12s ~ yearArrive, data = .)
lm3 <- df_baseline %>% lm_robust(pol12s ~ yearArrive, data = .)
lm4 <- df_baseline %>% lm_robust(soc12s ~ yearArrive, data = .)
lm5 <- df_baseline %>% lm_robust(econ12s ~ yearArrive, data = .)
lm6 <- df_baseline %>% lm_robust(psy12s ~ yearArrive, data = .)
lm7 <- df_baseline %>% lm_robust(nav12s ~ yearArrive, data = .)

texreg::screenreg(list(lm1, lm2, lm3, lm4, lm5, lm6, lm7), stars = c(0.01, 0.05, 0.1), include.ci = FALSE, custom.model.names = c("Overall", "Linguistic", "Political", "Social", "Economic", "Psychological", "Navigational"))
```

```{r}
df_baseline %>% 
  filter(yearArrive >= 2010) %>% 
  ggplot() +
  geom_smooth(aes(yearArrive, ipl12s), method = "loess")+
  scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  theme_ipsum()
```

```{r, out.width = "100%"}
df_baseline %>% 
  group_by(yearArrive) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  drop_na(yearArrive) %>% 
  filter(yearArrive >= 2010) %>% 
  mutate(yearArrive = as.integer(yearArrive)) %>%
  filter(yearArrive >= 2010) %>% 
  ggplot() +
  geom_smooth(aes(yearArrive, score), method = "loess")+
  scale_x_continuous(breaks = seq(2010, 2020, 2)) +
  theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  facet_wrap(vars(measure))
```


### Gender


```{r}
df_baseline %>%
  group_by(female) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>% 
  ggplot(aes(factor(female), ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```

```{r, out.width="100%"}
df_baseline %>% 
  group_by(female) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(female = fct_inorder(female, ipl12s) %>% fct_rev()) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>%
  ggplot(aes(factor(female), score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum()
```

Spider chart

```{r}
df_baseline %>% 
  select(female, contains("12s"), -ipl12s) %>% 
  group_by(female) %>% 
  summarize_all(mean, na.rm = T) %>% 
  ggradar(values = c("0", "0.4", "0.8"), grid.mid = 0.4, grid.max = 0.8, legend.title = "Female")
```


### Highest education level

```{r}
df_baseline %>% 
  group_by(educationLevel) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(educationLevel = fct_inorder(educationLevel, ipl12s) %>% fct_rev()) %>% 
  ggplot(aes(educationLevel, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum() +
  coord_flip()
```

```{r, out.width="100%"}
df_baseline %>%
  group_by(educationLevel) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(speak = fct_inorder(educationLevel, ipl12s) %>% fct_rev()) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  drop_na(educationLevel) %>% 
  ggplot(aes(educationLevel, score, weight = weight)) +
  geom_col() +
  theme_ipsum() +
  facet_wrap(vars(measure)) +
  coord_flip()
```


### English proficiency

#### Speak

```{r}
df_baseline %>% 
  group_by(speak) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(speak = fct_inorder(speak, ipl12s) %>% fct_rev()) %>% 
  ggplot(aes(speak, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum() +
  coord_flip()
```

```{r, out.width = "100%"}
df_baseline %>% 
  group_by(speak) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(speak = fct_inorder(speak, ipl12s) %>% fct_rev()) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(speak, score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum() + 
  coord_flip()
```

#### Read

```{r}
df_baseline %>% 
  group_by(read) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(read = fct_inorder(read, ipl12s) %>% fct_rev()) %>% 
  ggplot(aes(read, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```

```{r, out.width = "100%"}
df_baseline %>% 
  group_by(read) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(read = fct_inorder(read, ipl12s) %>% fct_rev()) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(read, score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum() + 
  coord_flip()
```

### Income

```{r}
df_baseline %>% 
  group_by(income) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>% 
  ggplot(aes(income, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```


```{r, out.width = "100%"}
df_baseline %>% 
  group_by(income) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(
    income = as_factor(income),
    income = fct_inorder(income, ipl12s) %>% fct_rev()
    ) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(income, score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum() + 
  coord_flip()
```


### Unemployment

```{r}
df_baseline %>% 
  group_by(unemployment) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>% 
  ggplot(aes(factor(unemployment), ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```


```{r, out.width = "100%"}
df_baseline %>%
  group_by(unemployment) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(
    unemployment = as_factor(unemployment),
    unemployment = fct_inorder(unemployment, ipl12s) %>% fct_rev()
    ) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(unemployment, score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum() + 
  coord_flip()
```

### Country of birth

```{r}
df_baseline %>% 
  group_by(bcountryBinned) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(bcountryBinned = fct_inorder(bcountryBinned, ipl12s) %>% fct_rev()) %>% 
  ggplot(aes(bcountryBinned, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```


```{r, out.width = "100%"}
df_baseline %>% 
  group_by(bcountryBinned) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  mutate(
    bcountryBinned = as_factor(bcountryBinned),
    bcountryBinned = fct_inorder(bcountryBinned, ipl12s) %>% fct_rev()
    ) %>%
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  ggplot(aes(bcountryBinned, score, weight = weight)) +
  geom_col() +
  facet_wrap(vars(measure)) +
  theme_ipsum() + 
  coord_flip()
```

### Household size

```{r}
df_baseline %>%
  filter(householdSize <= 11) %>% 
  group_by(householdSize) %>% 
  summarise(
    ipl12s = mean(ipl12s, na.rm = TRUE),
    weight = mean(weight, na.rm = TRUE)
    ) %>%
  drop_na() %>% 
  ggplot(aes(householdSize, ipl12s, weight = weight)) +
  geom_col() +
  theme_ipsum()
```


```{r, out.width = "100%"}
df_baseline %>% 
  group_by(householdSize) %>% 
  summarise_at(vars(contains("12s"), weight), mean, na.rm = T) %>%
  drop_na() %>%
  arrange(ipl12s) %>% 
  pivot_longer(
    cols = contains("12s"),
    names_to = "measure",
    values_to = "score"
  ) %>% 
  filter(measure != "ipl12s") %>% 
  drop_na(householdSize) %>% 
  filter(householdSize <= 11) %>% 
  mutate(householdSize = as.integer(householdSize)) %>%
  ggplot(aes(householdSize, score)) +
  geom_col() +
  scale_x_continuous(breaks = seq(0, 12, 2)) +
  theme_ipsum() +
  facet_wrap(vars(measure))
```

## Regressions

### Baseline characteristics

```{r}
lm1 <- df_baseline %>% lm_robust(ipl12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm2 <- df_baseline %>% lm_robust(ling12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm3 <- df_baseline %>% lm_robust(pol12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm4 <- df_baseline %>% lm_robust(soc12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm5 <- df_baseline %>% lm_robust(econ12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm6 <- df_baseline %>% lm_robust(psy12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm7 <- df_baseline %>% lm_robust(nav12s ~ female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)

screenreg(list(lm1, lm2, lm3, lm4, lm5, lm6, lm7), include.ci = FALSE, custom.model.names = c("Overall", "Linguistic", "Political", "Social", "Economic", "Psychological", "Navigational"))
```


```{r}
lm1 <- df_baseline %>% lm_robust(ipl12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm2 <- df_baseline %>% lm_robust(ling12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm3 <- df_baseline %>% lm_robust(pol12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm4 <- df_baseline %>% lm_robust(soc12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm5 <- df_baseline %>% lm_robust(econ12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm6 <- df_baseline %>% lm_robust(psy12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)
lm7 <- df_baseline %>% lm_robust(nav12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned, data = .)

screenreg(list(lm1, lm2, lm3, lm4, lm5, lm6, lm7), include.ci = FALSE, custom.model.names = c("Overall", "Linguistic", "Political", "Social", "Economic", "Psychological", "Navigational"))
```


```{r}
lm1 <- df_baseline %>% lm_robust(ipl12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm2 <- df_baseline %>% lm_robust(ling12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm3 <- df_baseline %>% lm_robust(pol12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm4 <- df_baseline %>% lm_robust(soc12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm5 <- df_baseline %>% lm_robust(econ12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm6 <- df_baseline %>% lm_robust(psy12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)
lm7 <- df_baseline %>% lm_robust(nav12s ~ years_in_us + female + age_at_arrival + educationLevel + read + speak + income + bcountryBinned + stateCurrent, data = .)

screenreg(list(lm1, lm2, lm3, lm4, lm5, lm6, lm7), include.ci = FALSE, custom.model.names = c("Overall", "Linguistic", "Political", "Social", "Economic", "Psychological", "Navigational"), omit.coef = "state")
```

