---
title: 'LIRS Sample weights'
author: "Michael Hotard and Saurabh Khanna"
date: "`r Sys.Date()`"
output:
  html_document:
    number_sections: no
    toc: yes
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = TRUE, fig.retina = 4)
knitr::opts_chunk$set(fig.pos = 'H')
```


## Load data

```{r}
# Libraries
# install.packages("pacman")
pacman::p_load(tidyverse, ebal, janitor)

# Sample data
df_sample <- read_csv(here::here("data", "Rapid_response_baseline_20200904.csv")) %>% clean_names()

# Population data
#df_population <- read_csv(here::here("data", "population_data.csv")) %>% clean_names()
```


## Creating dataframe for balance checks

```{r}
df_main <- 
  bind_rows(
    
    df_sample %>% 
      select(
        response_id,
        year_arrive,
        education_level, 
        gender, 
        q_language,	
        marital_status, 
        state_resettle, 
        bcountry
      ) %>% 
      mutate_all(as_factor),
    
    df_sample %>% 
      select(
        response_id,
        year_arrive,
        education_level, 
        gender, 
        q_language,	
        marital_status, 
        state_resettle, 
        bcountry
      ) %>% 
      mutate_all(as_factor) %>% 
      sample_frac(9, replace = TRUE),
    
    ## during the actual run, uncomment the population data below this line, and comment the dummy population above##
    # df_population %>% 
    #   select(
    #     year_arrive = arrival_cy,
    #     education_level, 
    #     gender, 
    #     q_language = survey_language,	
    #     marital_status, 
    #     state_resettle = state_resettled, 
    #     bcountry = country_birth
    #   ) %>% 
    #   mutate_all(as_factor)
    
    .id = "surveyed"
  ) %>%
  mutate(
    surveyed = parse_number(surveyed) - 1
  )

# check survey and population size
df_main %>% count(surveyed)
```


## Checking mean differences using t-tests

Might need to modify variable data types based on the 2 datasets

```{r}
# Gender
df_main %>%
  mutate(
    female = recode(gender, "Male" = "0", "Female" = "1", .default = NA_character_) %>% as.character %>% parse_integer(),
  ) %>%
  t.test(female ~ surveyed, data = .)

# Year of arrival
df_main %>%
  mutate(
    year_arrive = as.integer(year_arrive),
  ) %>%
  t.test(year_arrive ~ surveyed, data = .)


# add other relevant vars


# for significant ones, exclude NAs and reorder columns
df_main <- 
  df_main %>%
  mutate(
    female = recode(gender, "Male" = "0", "Female" = "1", .default = NA_character_) %>% as.character %>% parse_integer(),
    year_arrive = year_arrive %>% as.integer()
  ) %>% 
  drop_na(female, year_arrive) %>% 
  select(female, year_arrive, response_id, surveyed)


# check survey and population size
df_main %>% count(surveyed)
```


## Entropy balancing

```{r}
eb.out <- ebalance(Treatment = df_main$surveyed, X = df_main[ , 1:2])

weights_only <- eb.out$w %>% as_tibble()

sample_with_weights <-
  df_main %>% 
  filter(surveyed == 0) %>% 
  bind_cols(weights_only) %>% 
  select(response_id, weight = value, everything())
```


## Extract sample with weights

```{r}
sample_with_weights %>% 
  write_csv(here::here("data/sample_with_weights.csv"))
```


