---
title: 'Geographic distribution of baseline survey data'
author: "Michael Hotard and Saurabh Khanna"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_depth: 4
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 4
fontsize: 12pt
---

# Spatial plots

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.retina = 4)
knitr::opts_chunk$set(fig.pos = 'H')
```

```{r}
# Libraries
library(tidyverse)
library(sf)

# Parameters
df <- read_csv(here::here("data", "Rapid_response_baseline_cleaned.csv"))
df_weights <- read_csv(here::here("data", "weights.csv"))

df <- left_join(df, df_weights, by = "study_ID")
```


```{r}
# Obtaining state level mean stats 
df_states <-
  df %>%
  arrange(stateCurrent) %>%
  select(stateCurrent, unemploymentBeneBaseline, caresStimulusBaseline, foodSecurity1Baseline, housingRentBaseline, birthYear, yearArrive, householdSize, householdChildren, weight) %>% 
  left_join(df %>% count(stateCurrent), by = "stateCurrent") %>% 
  filter(n >= 10) %>%
  mutate(
    stateCurrent = if_else(stateCurrent == "Refused", NA_character_, stateCurrent),
    stateCurrent = if_else(stateCurrent == "I do not reside in the United States", NA_character_, stateCurrent),
    unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "Yes", "1", unemploymentBeneBaseline),
    unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "No", "0", unemploymentBeneBaseline),
    unemploymentBeneBaseline = unemploymentBeneBaseline %>% as.integer(),
    caresStimulusBaseline = if_else(caresStimulusBaseline == "Yes", "1", caresStimulusBaseline),
    caresStimulusBaseline = if_else(caresStimulusBaseline == "No", "0", caresStimulusBaseline),
    caresStimulusBaseline = caresStimulusBaseline %>% as.integer(),
    foodSecurity1Baseline = if_else(str_detect(foodSecurity1Baseline, "^Enough"), "0", foodSecurity1Baseline),
    foodSecurity1Baseline = if_else(str_detect(foodSecurity1Baseline, "not enough"), "1", foodSecurity1Baseline),
    foodSecurity1Baseline = if_else(foodSecurity1Baseline %in% c("0", "1"), foodSecurity1Baseline, NA_character_),
    foodSecurity1Baseline = foodSecurity1Baseline %>% as.integer(),
    housingRentBaseline = if_else(housingRentBaseline == "Yes", "1", housingRentBaseline),
    housingRentBaseline = if_else(housingRentBaseline == "No", "0", housingRentBaseline),
    housingRentBaseline = if_else(str_detect(housingRentBaseline, "^Payment"), "0", housingRentBaseline),
    housingRentBaseline = housingRentBaseline %>% as.integer()
  ) %>%
  drop_na(stateCurrent) %>% 
  group_by(stateCurrent) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>% 
  mutate_at(vars(birthYear, yearArrive, householdSize, householdChildren), ~ round(.))
```


## Number of respondents

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df %>% count(stateCurrent),
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = n), size = 0.3) +
  scale_fill_continuous(high = "#132B43", low = "#56B1F7") +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Number of respondents"
  )

ggsave("spatial_plots/figure_1.png")
```

## Unemployment benefits

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = unemploymentBeneBaseline), size = 0.3) +
  scale_fill_continuous(
    high = "#132B43", low = "#56B1F7",
    labels = scales::percent
  ) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Receiving unemployment benefits"
  )

ggsave("spatial_plots/figure_2.png")
```


## CARES Stimulus

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = caresStimulusBaseline), size = 0.3) +
  scale_fill_continuous(
    high = "#132B43", low = "#56B1F7",
    labels = scales::percent,
    breaks = seq(0.7, 1, 0.15)
  ) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Received CARES Stimulus"
  )

ggsave("spatial_plots/figure_3.png")
```


## Food Security

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = foodSecurity1Baseline), size = 0.3) +
  scale_fill_continuous(
    high = "#132B43", low = "#56B1F7",
    labels = scales::percent,
    breaks = seq(0, 1, 0.2)
  ) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Facing food insecurity"
  )

ggsave("spatial_plots/figure_4.png")
```


## Housing rent paid on time

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = housingRentBaseline), size = 0.3) +
  scale_fill_continuous(
    high = "#132B43", low = "#56B1F7",
    labels = scales::percent,
    breaks = seq(0, 1, 0.1)
  ) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Housing rent paid on time"
  )

ggsave("spatial_plots/figure_5.png")
```

## Year of arrival

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = factor(yearArrive)), size = 0.3) +
  theme_void() +
  scale_fill_brewer(na.value = "#757D75", breaks = seq(2010, 2020, 1)) +
  theme(legend.position = "bottom") +
  labs(
    fill = "Mean year of arrival"
  )

ggsave("spatial_plots/figure_6.png")
```


## Year of birth

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = as_factor(birthYear)), size = 0.3) +
  scale_fill_brewer(na.value = "#757D75", breaks = seq(1960, 1985, 1)) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Mean year of birth"
  )

ggsave("spatial_plots/figure_7.png")
```


## Household size

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = householdSize %>% as_factor()), size = 0.3) +
  scale_fill_brewer(na.value = "#757D75", breaks = seq(0, 10, 1)) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Mean household size"
  )

ggsave("spatial_plots/figure_8.png")
```


## Children in household

```{r}
ussf::boundaries(geography = "state") %>% 
  select(stateCurrent = NAME) %>% 
  left_join(
    df_states,
    by = "stateCurrent"
  ) %>% 
  ggplot() +
  geom_sf(aes(fill = householdChildren %>% as_factor()), size = 0.3) +
  scale_fill_brewer(na.value = "#757D75", breaks = seq(0, 5, 1)) +
  theme_void() +
  theme(legend.position = "bottom") +
  labs(
    fill = "Mean children in household"
  )

ggsave("spatial_plots/figure_9.png")
```

