---
title: "Survey Rates - October 2020"
author: "Saurabh Khanna"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: no
  html_document:
    toc: yes
    toc_depth: '3'
    df_print: paged
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE, fig.retina = 4)
knitr::opts_chunk$set(fig.pos = 'H')
```


\newpage

# Survey rates

```{r}
# Libraries
pacman::p_load(tidyverse, readxl, janitor, lubridate, extrafont, estimatr, fastDummies)
extrafont::loadfonts()
# Parameters
df_baseline <- read_csv(here::here("data", "Rapid_response_baseline_cleaned_all_consent.csv"))

df_updated <- 
  read_xlsx(here::here("data/merge", "lirs_postresponses_updated_all.xlsx")) %>% 
  mutate(
    number_from = parse_number(number_from) %>% as.character(),
    date = as_datetime(date),
    wave = str_c(month(date), year(date), sep = "-")
  ) %>% count(wave) 
  arrange(number_from, desc(date)) %>%
  filter(wave == "10-2020") %>%  # adjust wave here as needed
  distinct(number_from, .keep_all = TRUE) %>%
  drop_na(number_from)


df_whatsapp_twilio <- read_xlsx(here::here("data/merge", "whatsapp_twilio.xlsx"))
df_sms_twilio <- read_xlsx(here::here("data/merge", "sms_twilio.xlsx"))

df_twilio <- 
  bind_rows(
    df_whatsapp_twilio %>% select(study_ID, number_from = whatsAppNumber_final, lang = languageFollowUps), 
    df_sms_twilio %>% select(study_ID, number_from = smsNumber_final, lang = languageFollowUps),
    .id = "medium"
  ) %>% 
  mutate(
    medium = recode(medium, `1` = "WhatsApp", `2` = "SMS", .default = NA_character_),
  ) %>% 
  distinct(study_ID, .keep_all = TRUE) %>% 
  distinct(number_from, .keep_all = TRUE)

# df_nomatch <- read_xlsx(here::here("data", "merge/lirs_postresponses_nomatch_all_september.xlsx"))
failed_nos <- 
  read_csv(here::here("data", "merge/failed_messages.csv")) %>% 
  mutate(number_from = parse_number(`To Number`) %>% as.character()) %>% 
  distinct(number_from) %>% 
  unlist()

rm(df_whatsapp_twilio, df_sms_twilio)
```


```{r}
df_main <-
  df_baseline %>% 
  inner_join(df_twilio, ., by = "study_ID") %>%
  inner_join(df_updated, by = "number_from") %>% 
  filter(!(number_from %in% failed_nos)) %>%
  mutate(
    lang = if_else(lang %in% c("Don't know", "Refused"), NA_character_, lang),
    lang_match = 
      case_when(
        lang == "Arabic" & Arabic %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Dari/Farsi" & Farsi %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Dari/Farsi" & Dari %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "English" & English %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Farsi" & Farsi %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Farsi" & Dari %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "French" & French %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Russian" & Russian %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Spanish" & Spanish %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        lang == "Swahili" & Swahili %in% c("NATIVE", "R", "RW", "W", "R NATIVE", "RW NATIVE") ~ "Match",
        TRUE ~ "No match"
      )
  )
```



```{r}
## For PoliSci paper

# df_main %>%
#   mutate(
#     survey_started = q1_response != "No Data",
#     survey_completed = q18_response != "No Data"
#   ) %>% 
#   filter(medium == "WhatsApp", survey_completed) %>% 
#   mutate(
#     id_matched = (yearArrive == q18_response)
#   ) %>% 
#   count(id_matched)
```



```{r}
## Balance tables

# df_balance <-
#   df_main %>%
#   filter(medium == "WhatsApp") %>%
#   mutate(
#     survey_completed = q18_response != "No Data",
#     bal_match = if_else(survey_completed & yearArrive == q18_response, 1L, 0L),
#     bal_match = if_else(is.na(bal_match), 0L, bal_match),
#     female = recode(gender, "Male" = "0", "Female" = "1", .default = "0") %>% as.character %>% parse_integer(),
#     unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "Yes", "1", unemploymentBeneBaseline),
#     unemploymentBeneBaseline = if_else(unemploymentBeneBaseline == "No", "0", unemploymentBeneBaseline),
#     unemployment = unemploymentBeneBaseline %>% as.integer()  
#   ) %>% 
#   select(bal_match, birthYear, female, unemployment, income, famsize = householdSize, country = bcountryBinned) %>% 
#   dummy_cols(select_columns = "country", ignore_na = TRUE) %>% 
#   rename(country_Congo = `country_Congo - Kinshasa`)
# 
# haven::write_dta(df_balance, "df_balance.dta", version = 13)
# 
# t.test(birthYear ~ bal_match, data = df_balance)
# t.test(female ~ bal_match, data = df_balance)
# t.test(unemployment ~ bal_match, data = df_balance)
# t.test(famsize ~ bal_match, data = df_balance)
# t.test(income ~ bal_match, data = df_balance)
# t.test(country_Iraq ~ bal_match, data = df_balance)
# t.test(country_Congo ~ bal_match, data = df_balance)
# t.test(country_Afghanistan ~ bal_match, data = df_balance)
# t.test(country_Ukraine ~ bal_match, data = df_balance)
# t.test(country_Somalia ~ bal_match, data = df_balance)
# t.test(country_Other ~ bal_match, data = df_balance)
# 
# lm_robust(birthYear ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(female ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(unemployment ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(income ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(famsize ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Iraq ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Congo ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Afghanistan ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Ukraine ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Somalia ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
# lm_robust(country_Other ~ bal_match, data = df_balance, se_type = "stata") %>% summary()
```


```{r, eval=F}
## Raw logs

# Joining raw logs into 1 file
# setwd("D:/Everything/GitHub/ipl-lirs/data/raw_logs")
# df_raw <- plyr::ldply(list.files(), read.csv, header=TRUE) %>% as_tibble()
# setwd(here::here())
```


```{r, eval=F}
# survey_dates <-
#   df_raw %>%
#   filter(str_detect(`To`, "whatsapp")) %>% 
#   mutate(
#     number_from = parse_number(To) %>% as.character(),
#     survey_date = as_date(SentDate)
#   ) %>% 
#   inner_join(df_main, by = "number_from") %>% 
#   arrange(number_from, desc(survey_date)) %>% 
#   distinct(number_from, .keep_all = T) %>% 
#   select(number_from, survey_date)
# 
# vasco_file <-
#   df_raw %>%
#   filter(str_detect(`To`, "whatsapp")) %>% 
#   mutate(
#     number_from = parse_number(To) %>% as.character(),
#     timestamp = as_datetime(SentDate),
#     survey_date = as_date(SentDate)
#   ) %>%
#   relocate(number_from, timestamp, survey_date) %>% 
#   inner_join(df_main, by = "number_from") %>%
#   filter(q18_response != "No Data") %>% 
#   inner_join(survey_dates, by = c("number_from", "survey_date")) %>%
#   arrange(number_from, timestamp) %>% 
#   group_by(number_from) %>% 
#   summarize(
#     messages = n(),
#     duration = interval(first(timestamp), last(timestamp)) %>% time_length("minute")
#   )
# 
# vasco_file %>% 
#   ggplot(aes(messages, stat(count)))+
#   geom_histogram(fill = "gray", color = "black") +
#   stat_bin(aes(y = cumsum(..count..)), geom = "step") +
#   hrbrthemes::theme_ipsum()
```



## Figures (Overall)

```{r, fig.asp = 1}
df_main %>%
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = everything(), names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        medium,
        lang,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = everything(), names_to = "name", values_to = "count"),
    by = "name"
  ) %>% 
  knitr::kable()

df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = everything(), names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  labs(
    x = "",
    y = "Survey rate"
  )
```

\newpage

## By medium

```{r, fig.asp = 0.8}
df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  group_by(medium) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -medium, names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        medium,
        lang,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      group_by(medium) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = -medium, names_to = "name", values_to = "count"),
    by = c("medium", "name")
  ) %>% 
  arrange(medium) %>% 
  knitr::kable()

df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>%
  group_by(medium) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -medium, names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  facet_wrap(vars(medium)) +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(
    x = "",
    y = "Survey rate"
  )
```

\newpage

## By language

```{r, fig.asp =  1.5}
df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  group_by(lang) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -lang, names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        medium,
        lang,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      group_by(lang) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = -lang, names_to = "name", values_to = "count"),
    by = c("lang", "name")
  ) %>% 
  drop_na(lang) %>% 
  arrange(lang) %>% 
  knitr::kable()


df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>%
  group_by(lang) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>%
  drop_na(lang) %>% 
  pivot_longer(cols = -lang, names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  facet_wrap(vars(lang)) +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(
    x = "",
    y = "Survey rate"
  )
```

\newpage

## By medium and language

```{r, fig.asp = 3}
df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  group_by(medium, lang) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -c(medium, lang), names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        medium,
        lang,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      group_by(medium, lang) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = -c(medium, lang), names_to = "name", values_to = "count"),
    by = c("medium", "lang", "name")
  ) %>%
  drop_na(lang) %>% 
  arrange(medium, lang) %>% 
  knitr::kable()

df_main %>% 
  transmute(
    medium,
    lang,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>%
  group_by(medium, lang) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>%
  drop_na(lang) %>% 
  pivot_longer(cols = -c(lang, medium), names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  facet_grid(rows = vars(lang), cols = vars(medium)) +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(
    x = "",
    y = "Survey rate"
  )
```

\newpage

## By language proficiency

`lang_match` highlights if the respondent was proficient in the followup survey language.

```{r, fig.asp=0.8}
df_main %>% 
  transmute(
    lang_match,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  group_by(lang_match) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -lang_match, names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        lang_match,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      group_by(lang_match) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = -lang_match, names_to = "name", values_to = "count"),
    by = c("lang_match", "name")
  ) %>% 
  arrange(lang_match) %>% 
  knitr::kable()

df_main %>% 
  transmute(
    lang_match,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>%
  group_by(lang_match) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -lang_match, names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  facet_wrap(vars(lang_match)) +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(
    x = "",
    y = "Survey rate"
  )
```


\newpage

## By medium and language proficiency

```{r, fig.asp = 1}
df_main %>% 
  transmute(
    medium,
    lang_match,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>% 
  group_by(medium, lang_match) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>% 
  pivot_longer(cols = -c(medium, lang_match), names_to = "name", values_to = "proportion") %>%
  full_join(
    df_main %>% 
      transmute(
        medium,
        lang_match,
        survey_started = if_else(q1_response != "No Data", 1, 0),
        survey_completed = if_else(q18_response != "No Data", 1, 0)
      ) %>% 
      group_by(medium, lang_match) %>% 
      summarize(
        `Survey started` = sum(survey_started, na.rm = TRUE),
        `Survey completed` = sum(survey_completed, na.rm = TRUE),
        `Total` = sum(n(), na.rm = TRUE)
      ) %>% 
      pivot_longer(cols = -c(medium, lang_match), names_to = "name", values_to = "count"),
    by = c("medium", "lang_match", "name")
  ) %>%
  drop_na(lang_match) %>% 
  arrange(medium, lang_match) %>% 
  knitr::kable()

df_main %>% 
  transmute(
    medium,
    lang_match,
    survey_started = if_else(q1_response != "No Data", 1, 0),
    survey_completed = if_else(q18_response != "No Data", 1, 0)
  ) %>%
  group_by(medium, lang_match) %>% 
  summarize(
    `Survey started` = mean(survey_started, na.rm = TRUE),
    `Survey completed` = mean(survey_completed, na.rm = TRUE)
  ) %>% 
  mutate(`Completed if started` = `Survey completed` / `Survey started`) %>%
  drop_na(lang_match) %>% 
  pivot_longer(cols = -c(lang_match, medium), names_to = "name", values_to = "value") %>% 
  mutate(name = factor(name, levels = c("Survey started", "Survey completed", "Completed if started"))) %>% 
  ggplot(aes(name, value)) +
  geom_col(color = "black") +
  facet_grid(rows = vars(lang_match), cols = vars(medium)) +
  scale_y_continuous(
    # breaks = scales::breaks_width(0.2),
    labels = scales::percent_format(accuracy = 1)
  ) +
  hrbrthemes::theme_ipsum() +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  labs(
    x = "",
    y = "Survey rate"
  )
```

